version: 2.1

jobs:
  verify_build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:<< parameters.python >>
    parameters:
      python:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.python >>-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-<< parameters.python >>--
      - run:
        name: Install Dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run:
        name: Run Unit Tests
        command: |
          . venv/bin/activate
          nose2 -v
      - run:
        name: Run Unit Tests
        command: |
          . venv/bin/activate
          flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-<< parameters.python >>-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

workflows:
  python-v2.7:
    jobs:
      - verify_build:
          python: "2.7"

  python-v3.6:
    jobs:
      - verify_build:
          python: "3.6"

  python-v3.7:
    jobs:
      - verify_build:
          python: "3.7"
