name: update-deps

on:
  schedule:
    - cron: "0 10 * * *" # Run at 10 am every day
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    environment:
      name: protected-main-env
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Update Dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry build
          poetry update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update dependencies
          title: Update Dependencies
          body: |
            Autogenerated PR to update all deps to latest versions
          branch: update-dependencies
